In [1]:
import pandas as pd
import numpy as np

In [2]:
ts1 = pd.Series(np.random.randn(9), index=[
     ['a','a','a','b','b','c','c','d','d'],
     [ 1,  2,  3,  1,  3,  1,  2,  2,  3]                                      
])

In [3]:
ts1

a  1   -0.047536
   2    2.357264
   3    1.624207
b  1    0.895235
   3    0.572232
c  1    1.038336
   2    1.311757
d  2   -0.450875
   3   -0.201640
dtype: float64

In [4]:
ts1.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [5]:
ts1['a']

1   -0.047536
2    2.357264
3    1.624207
dtype: float64

In [6]:
ts1['b']

1    0.895235
3    0.572232
dtype: float64

In [7]:
ts1['b':'c']

b  1    0.895235
   3    0.572232
c  1    1.038336
   2    1.311757
dtype: float64

In [8]:
ts1.loc[['b','d']]

b  1    0.895235
   3    0.572232
d  2   -0.450875
   3   -0.201640
dtype: float64

In [9]:
ts1.loc[:,2]

a    2.357264
c    1.311757
d   -0.450875
dtype: float64

In [10]:
ts1

a  1   -0.047536
   2    2.357264
   3    1.624207
b  1    0.895235
   3    0.572232
c  1    1.038336
   2    1.311757
d  2   -0.450875
   3   -0.201640
dtype: float64

In [12]:
df1 = ts1.unstack()

In [13]:
df1

1         2         3
a -0.047536  2.357264  1.624207
b  0.895235       NaN  0.572232
c  1.038336  1.311757       NaN
d       NaN -0.450875 -0.201640

In [14]:
ts2 = df1.stack()

In [15]:
ts2

a  1   -0.047536
   2    2.357264
   3    1.624207
b  1    0.895235
   3    0.572232
c  1    1.038336
   2    1.311757
d  2   -0.450875
   3   -0.201640
dtype: float64

In [16]:
ts1.unstack().stack()

a  1   -0.047536
   2    2.357264
   3    1.624207
b  1    0.895235
   3    0.572232
c  1    1.038336
   2    1.311757
d  2   -0.450875
   3   -0.201640
dtype: float64

In [17]:
ts1

a  1   -0.047536
   2    2.357264
   3    1.624207
b  1    0.895235
   3    0.572232
c  1    1.038336
   2    1.311757
d  2   -0.450875
   3   -0.201640
dtype: float64

In [18]:
ts1.index.names = ['k1', 'k2']

In [20]:
ts1

k1  k2
a   1    -0.047536
    2     2.357264
    3     1.624207
b   1     0.895235
    3     0.572232
c   1     1.038336
    2     1.311757
d   2    -0.450875
    3    -0.201640
dtype: float64

In [21]:
df2 = pd.DataFrame(np.arange(12).reshape((4,3)), index=[['a','a','b','b'],[1,2,1,2]], columns=[['marmara','marmara','ege'],['istanbul','tekirdag','izmir']])

In [22]:
df2

marmara            ege
    istanbul tekirdag izmir
a 1        0        1     2
  2        3        4     5
b 1        6        7     8
  2        9       10    11

In [23]:
df2['marmara']

istanbul  tekirdag
a 1         0         1
  2         3         4
b 1         6         7
  2         9        10

In [24]:
df2.index.names = ['k1', 'k2']

In [25]:
df2

marmara            ege
      istanbul tekirdag izmir
k1 k2                        
a  1         0        1     2
   2         3        4     5
b  1         6        7     8
   2         9       10    11

In [26]:
df2.sum(level='k2')

marmara            ege
   istanbul tekirdag izmir
k2                        
1         6        8    10
2        12       14    16

In [27]:
df2.columns.names=['region','city']

In [28]:
df2

region  marmara            ege
city   istanbul tekirdag izmir
k1 k2                         
a  1          0        1     2
   2          3        4     5
b  1          6        7     8
   2          9       10    11

In [30]:
df2.sum(level='region', axis=1)

region  marmara  ege
k1 k2               
a  1          1    2
   2          7    5
b  1         13    8
   2         19   11

In [32]:
df3 = pd.DataFrame({
    'key': ['b','b','a','c','a','a','b'],
    'data1': range(7)
})
df4 = pd.DataFrame({
    'key': ['a','b','d'],
    'data2': range(3)
})

In [33]:
df3

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [34]:
df4

key  data2
0   a      0
1   b      1
2   d      2

In [35]:
df5 = pd.merge(df3,df4,on = "key")

In [36]:
df5

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [38]:
df6 = pd.merge(df3,df4,how="outer")

In [39]:
df6

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [40]:
df7 = pd.merge(df3,df4,how="left")

In [41]:
df7

key  data1  data2
0   b      0    1.0
1   b      1    1.0
2   a      2    0.0
3   c      3    NaN
4   a      4    0.0
5   a      5    0.0
6   b      6    1.0

In [42]:
df8 = pd.merge(df3,df4,how="right")

In [43]:
df8

key  data1  data2
0   a    2.0      0
1   a    4.0      0
2   a    5.0      0
3   b    0.0      1
4   b    1.0      1
5   b    6.0      1
6   d    NaN      2

In [50]:
arr1 = np.arange(12).reshape((3,4))
arr4 = np.arange(12).reshape((4,3))

In [45]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
arr2 = np.concatenate([arr1, arr1], axis=0)

In [47]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
arr3 = np.concatenate([arr1, arr1], axis=1)

In [49]:
arr3

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [51]:
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
try:
  arr5 = np.concatenate([arr1, arr4], axis=0)
except ValueError as err:
  print(err)  

all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3


In [55]:
ts3 = pd.Series([0,1], index=['a','b'])
ts4 = pd.Series([2,3,4], index=['c','d','e'])
ts5 = pd.Series([5,6], index=['f','g'])

In [61]:
ts6 = pd.concat([ts3, ts4, ts5], axis=0)

In [62]:
ts6

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [65]:
ts3 = pd.Series([0,1,42], index=['a','b','c'])
ts4 = pd.Series([2,3,4], index=['c','d','e'])
ts5 = pd.Series([108, 5,6], index=['c','f','g'])

In [68]:
ts7 = pd.concat([ts3, ts4, ts5], axis=1, join='inner')

In [70]:
ts7

0  1    2
c  42  2  108

In [71]:
countries_df = pd.read_json("sample_data/countries.json")

In [77]:
countries_df.columns

Index(['_id', 'continent', 'gnp', 'governmentForm', 'headOfState',
       'lifeExpectancy', 'localName', 'name', 'population', 'region',
       'surfaceArea', 'indepYear'],
      dtype='object')

In [76]:
del countries_df['cities']

In [78]:
countries_df.head(5)

_id      continent  ...  surfaceArea indepYear
0  ABW  North America  ...        205.0       NaN
1  AFG           Asia  ...     652102.0    1919.0
2  AGO         Africa  ...    1246712.0    1975.0
3  AIA  North America  ...        108.0       NaN
4  ALB         Europe  ...      28760.0    1912.0

[5 rows x 12 columns]

In [84]:
countries_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239 entries, 0 to 238
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   _id             239 non-null    object 
 1   continent       239 non-null    object 
 2   gnp             239 non-null    float64
 3   governmentForm  239 non-null    object 
 4   headOfState     238 non-null    object 
 5   lifeExpectancy  222 non-null    float64
 6   localName       239 non-null    object 
 7   name            239 non-null    object 
 8   population      239 non-null    int64  
 9   region          239 non-null    object 
 10  surfaceArea     239 non-null    float64
 11  indepYear       192 non-null    float64
dtypes: float64(4), int64(1), object(7)
memory usage: 22.5+ KB


In [81]:
ulkeler = countries_df.dropna()

In [83]:
ulkeler.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 190 entries, 1 to 238
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   _id             190 non-null    object 
 1   continent       190 non-null    object 
 2   gnp             190 non-null    float64
 3   governmentForm  190 non-null    object 
 4   headOfState     190 non-null    object 
 5   lifeExpectancy  190 non-null    float64
 6   localName       190 non-null    object 
 7   name            190 non-null    object 
 8   population      190 non-null    int64  
 9   region          190 non-null    object 
 10  surfaceArea     190 non-null    float64
 11  indepYear       190 non-null    float64
dtypes: float64(4), int64(1), object(7)
memory usage: 19.3+ KB


In [85]:
df10 = pd.DataFrame({
    "key": ["jack", "kate", "james"],
    "age": [48, 39, 42],
    "salary": [100_000, 200_000, 300_000],
    "department": ["IT", "SALES", "FINANCE"] 
})

In [86]:
df10

key  age  salary department
0   jack   48  100000         IT
1   kate   39  200000      SALES
2  james   42  300000    FINANCE

In [87]:
melted_df = pd.melt(df10, ["key"])

In [88]:
melted_df

key    variable    value
0   jack         age       48
1   kate         age       39
2  james         age       42
3   jack      salary   100000
4   kate      salary   200000
5  james      salary   300000
6   jack  department       IT
7   kate  department    SALES
8  james  department  FINANCE

In [89]:
melted_df2 = pd.melt(df10, ["department"])

In [91]:
melted_df2[melted_df2.department == 'IT']

department variable   value
0         IT      key    jack
3         IT      age      48
6         IT   salary  100000

In [92]:
melted_df[melted_df.key == 'jack']

key    variable   value
0  jack         age      48
3  jack      salary  100000
6  jack  department      IT

In [93]:
df11 = melted_df.pivot('key','variable','value')

In [94]:
df11

variable age department  salary
key                            
jack      48         IT  100000
james     42    FINANCE  300000
kate      39      SALES  200000

In [95]:
countries_df

_id      continent  ...  surfaceArea indepYear
0    ABW  North America  ...        205.0       NaN
1    AFG           Asia  ...     652102.0    1919.0
2    AGO         Africa  ...    1246712.0    1975.0
3    AIA  North America  ...        108.0       NaN
4    ALB         Europe  ...      28760.0    1912.0
..   ...            ...  ...          ...       ...
234  YEM           Asia  ...     527980.0    1918.0
235  YUG         Europe  ...     102185.0    1918.0
236  ZAF         Africa  ...    1221049.0    1910.0
237  ZMB         Africa  ...     752630.0    1964.0
238  ZWE         Africa  ...     390769.0    1980.0

[239 rows x 12 columns]

In [96]:
melted_countries = pd.melt(countries_df, ["_id"] )

In [97]:
melted_countries.head(10)

_id   variable          value
0  ABW  continent  North America
1  AFG  continent           Asia
2  AGO  continent         Africa
3  AIA  continent  North America
4  ALB  continent         Europe
5  AND  continent         Europe
6  ANT  continent  North America
7  ARE  continent           Asia
8  ARG  continent  South America
9  ARM  continent           Asia