In [1]:
#!pip install numpy
import numpy as np # c library
print(np.__version__)

1.19.5


In [ ]:
# "numeric python" -> numpy
# 1. Fast (implemented in C)
# 2. element-wise: /,*,+,... 
# 3. homogeneous: int, float, str, ...

In [2]:
mylist = list(range(10_000_000)) # python's list

In [3]:
arr = np.arange(10_000_000) # numpy array

In [4]:
%time for i in range(10): arr2 = arr * 2  

CPU times: user 224 ms, sys: 90.9 ms, total: 314 ms
Wall time: 321 ms


In [5]:
%time for i in range(10): mylist2 = [x*2 for x in mylist]

CPU times: user 7.72 s, sys: 1.85 s, total: 9.56 s
Wall time: 9.56 s


In [7]:
arr3 = 2 * arr1 + arr2

In [10]:
numbers = [4,8,15,16,23,42]

In [ ]:
numbers * 4

In [12]:
[x*2 for x in numbers]

[8, 16, 30, 32, 46, 84]

In [13]:
numbers + numbers

[4, 8, 15, 16, 23, 42, 4, 8, 15, 16, 23, 42]

In [16]:
arr4 = np.array([4,8,15,16,23,42])

In [19]:
arr4 // 2

array([ 2,  4,  7,  8, 11, 21])

In [20]:
data1 = np.random.randn(3,4)

In [21]:
type(data1)

numpy.ndarray

In [32]:
data2 = np.array([[1,2.,3],[4,5,6]])

In [23]:
type(data2)

numpy.ndarray

In [24]:
data1.shape

(3, 4)

In [25]:
data2.shape

(2, 3)

In [26]:
data1.dtype

dtype('float64')

In [33]:
data2.dtype

dtype('float64')

In [34]:
data3 = np.array([True, False, False, True])

In [35]:
data3.dtype

dtype('bool')

In [36]:
data4 = np.array(["jack", "kate", "james", "ben"])

In [37]:
data4.dtype

dtype('<U5')

In [38]:
# numpy array: dtype, shape, ndim

In [39]:
data1.dtype

dtype('float64')

In [40]:
data1.shape

(3, 4)

In [41]:
data1.ndim

2

In [43]:
data5 = np.array([[[1,2,3],[3,4,5]],[[1,2,3],[3,4,5]]])

In [44]:
print(data5.dtype, data5.shape, data5.ndim)

int64 (2, 2, 3) 3


In [45]:
#1 list   -> np.array([1,2,3])
#2 random -> np.random.randint(3,4,5)
#3 0 , 1  -> np.zeros((3,4,5)), np.ones((3,4,5))

In [46]:
data6 = np.zeros((3,4,5))

In [47]:
data6

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [48]:
data7 = np.ones((3,4,5))

In [49]:
data7

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [50]:
data8 = np.array(['U20BA', 2, 3], dtype=np.unicode_)

In [51]:
data8.dtype

dtype('<U5')

In [56]:
data9 = np.array([2, 2, 3, 1_000_000], dtype=np.int8)

In [62]:
data9.dtype

dtype('int8')

In [59]:
data9

array([ 2,  2,  3, 64], dtype=int8)

In [63]:
data11 = data9.astype(np.float64)

In [64]:
data11.dtype

dtype('float64')

In [54]:
data10 = np.array([2, 2, 3])

In [55]:
data10.dtype

dtype('int64')