In [2]:
# Import numpy as np and print the version number.
import numpy as np
print(np.__version__)

1.19.5


In [5]:
# Create a 1D array of numbers from 0 to 9
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
# Create a 3×3 numpy array of all True’s
arr = np.full((3,3), True)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [11]:
# Extract all odd numbers from arr
arr = np.arange(10)
arr[arr%2 != 0]

array([1, 3, 5, 7, 9])

In [14]:
# Replace all odd numbers in arr with -1
arr = np.arange(10)
print(arr)
arr[arr%2 != 0]=-1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [20]:
# Replace all odd numbers in arr with -1 without changing arr
arr = np.arange(10)
out = np.where(arr%2 != 0 , -1 , arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [23]:
# Convert a 1D array to a 2D array with 2 rows
arr = np.arange(10)
out = arr.reshape(2,-1)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [35]:
# Stack arrays a and b vertically
a = np.arange(0,10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
c = np.concatenate([a,b],axis=0)
c = np.vstack([a,b])
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [36]:
# Stack arrays a and b horizontally
a = np.arange(0,10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
c = np.concatenate([a,b],axis=1)
c = np.hstack([a,b])
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [43]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3) , np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [45]:
# Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [46]:
# From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [48]:
# Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

In [55]:
# Get all items between 5 and 10 from a
a = np.array([2, 6, 1, 9, 10, 3, 27])

# solution #1
out = np.where( (a>4) & (a<10))
print(out)
print(a[out])

# solution #2
out = np.where( np.logical_and(a>4,a<10))
print(out)
print(a[out])

# solution #3
out = a[(a>4) & (a<10)]
print(out)

(array([1, 3]),)
[6 9]
(array([1, 3]),)
[6 9]
[6 9]


In [57]:
# Get all items between 5 and 10 from a
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [59]:
# Swap columns 1 and 2 in the array arr
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [63]:
# Reverse the rows of a 2D array arr
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [65]:
# Compute the moving average of window size 3, for the given 1D array
np.random.seed(100)
Z = np.random.randint(10, size=10)
print(Z)
np.convolve(Z, np.ones(3)/3, mode='valid')

[8 8 3 7 7 0 4 2 5 2]


array([6.33333333, 6.        , 5.66666667, 4.66666667, 3.66666667,
       2.        , 3.66666667, 3.        ])